"""Create user table

Revision ID: b2b0856095e1
Revises: da5e0a957139
Create Date: 2024-04-08 14:01:47.238247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b0856095e1'
down_revision: Union[str, None] = 'da5e0a957139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_fighters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fighter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fighters')
    op.drop_table('users')
    # ### end Alembic commands ###
