"""Fighter default

Revision ID: bcd1a155e417
Revises: b2b0856095e1
Create Date: 2024-04-08 14:57:37.247412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd1a155e417'
down_revision: Union[str, None] = 'b2b0856095e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'is_default')
    # ### end Alembic commands ###
